

export const actions = {
ADD_USER_SUCCESS : 'ADD_USER_SUCCESS',
ADD_USER_ERROR : 'ADD_USER_ERROR',
GET_USER_SUCCESS : 'GET_USER_SUCCESS',
START_GAME: 'START_GAME',
USER_START_GAME: 'USER_START_GAME',
GET_ALL_PLAYERS: 'GET_ALL_PLAYERS',
CHANGE_TO_SEEN:'CHANGE_TO_SEEN',
CHANGE_TO_FOLDED:'CHANGE_TO_FOLDED',
CHANGE_BET_AMOUNT:'CHANGE_BET_AMOUNT'
}

